# Generated by Django 6.0.7 on 2026-07-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('umg_id', models.AutoField(db_column='UMG_ID', primary_key=True, serialize=False)),
                ('umg_fecha', models.DateField(db_column='UMG_Fecha')),
                ('umg_hora_inicio', models.TimeField(db_column='UMG_Hora_Inicio')),
                ('umg_hora_fin', models.TimeField(db_column='UMG_Hora_Fin')),
                ('umg_tipo', models.CharField(db_column='UMG_Tipo', max_length=30)),
                ('umg_motivo', models.CharField(db_column='UMG_Motivo', max_length=150)),
                ('umg_estado', models.IntegerField(db_column='UMG_Estado', default=1)),
                ('umg_fecha_registro', models.DateTimeField(auto_now_add=True, db_column='UMG_Fecha_Registro')),
                ('umg_lab', models.ForeignKey(blank=True, db_column='UMG_Lab_ID', null=True, on_delete=django.db.models.deletion.RESTRICT, to='labs.lab')),
            ],
            options={
                'db_table': 'UMG_CONDI',
            },
        ),
    ]
