# Generated by Django 6.0.7 on 2026-07-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('umg_id', models.AutoField(db_column='UMG_ID', primary_key=True, serialize=False)),
                ('umg_nombre', models.CharField(db_column='UMG_Nombre', max_length=30, unique=True)),
                ('umg_descripcion', models.CharField(blank=True, db_column='UMG_Descripcion', max_length=150, null=True)),
                ('umg_estado', models.IntegerField(db_column='UMG_Estado', default=1)),
                ('umg_fecha_registro', models.DateTimeField(auto_now_add=True, db_column='UMG_Fecha_Registro')),
            ],
            options={
                'db_table': 'UMG_ROLES',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('umg_id', models.AutoField(db_column='UMG_ID', primary_key=True, serialize=False)),
                ('umg_usuario', models.CharField(db_column='UMG_Usuario', max_length=100, unique=True)),
                ('umg_contrasena', models.CharField(db_column='UMG_Contrasena', max_length=255)),
                ('umg_nombre', models.CharField(db_column='UMG_Nombre', max_length=50)),
                ('umg_apellido', models.CharField(db_column='UMG_Apellido', max_length=50)),
                ('umg_estado', models.IntegerField(db_column='UMG_Estado', default=1)),
                ('umg_ingreso', models.IntegerField(db_column='UMG_Ingreso', default=0)),
                ('umg_fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='UMG_Fecha_Creacion')),
                ('umg_fecha_modifica_contrasena', models.DateTimeField(blank=True, db_column='UMG_Fecha_Modifica_Contrasena', null=True)),
                ('umg_ultimo_acceso', models.DateTimeField(blank=True, db_column='UMG_Ultimo_Acceso', null=True)),
                ('umg_rol', models.ForeignKey(db_column='UMG_Rol_ID', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.rol')),
            ],
            options={
                'db_table': 'UMG_USERS',
            },
        ),
    ]
