# Generated by Django 6.0.7 on 2026-07-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('umg_id', models.BigAutoField(db_column='UMG_ID', primary_key=True, serialize=False)),
                ('umg_accion', models.CharField(db_column='UMG_Accion', max_length=50)),
                ('umg_modulo', models.CharField(db_column='UMG_Modulo', max_length=50)),
                ('umg_descripcion', models.TextField(db_column='UMG_Descripcion')),
                ('umg_fecha_registro', models.DateTimeField(auto_now_add=True, db_column='UMG_Fecha_Registro')),
                ('umg_user', models.ForeignKey(blank=True, db_column='UMG_User_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'UMG_LOG',
            },
        ),
    ]
