# Generated by Django 6.0.7 on 2026-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('umg_id', models.AutoField(db_column='UMG_ID', primary_key=True, serialize=False)),
                ('umg_nombre', models.CharField(db_column='UMG_Nombre', max_length=30, unique=True)),
                ('umg_estado', models.IntegerField(db_column='UMG_Estado', default=1)),
                ('umg_reserva', models.CharField(db_column='UMG_Reserva', default='D', max_length=1)),
                ('umg_fecha_registro', models.DateTimeField(auto_now_add=True, db_column='UMG_Fecha_Registro')),
            ],
            options={
                'db_table': 'UMG_LABS',
            },
        ),
    ]
